### ISSUE TITLE
question: where to put static assets and how to reference them?

### ISSUE THREAD

**Issue by Dmitry-N-Medvedev** [richardkall/react-starter#3]
I'd like to use a PNG icon on a page. Where should I put it on the file system to be able to reference it from CSS?

**Comment by richardkall** [comment]
Just reference the images relatively to your CSS. I would probably store the image inside the component's folder and reference them like this. 

`
background: url('./cat.jpg');
`

URL-loader will then take care if it and return a data-uri if the image size is below the limit specified in `webpack.config.babel.js`. I've set it to 10 KB.

Another solution would be to create a folder for all assets and serve it using Express:

```
application.use(express.static(path.join(__dirname, 'public')));
```

**Comment by Dmitry-N-Medvedev** [comment]
Thanks! express.static did the trick :)
