### ISSUE TITLE
HMR

### ISSUE THREAD

**Issue by Vistur** [richardkall/react-starter#5]
Is hot module replacement really working?
I run `npm run start-dev` then I edit App.js container and I don't see the changes. 
Instead I see two warnings in the console:
[HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html for more details. main.js:1641
[HMR]  - ./client/containers/App/App.js main.js:1649

Am I missing something? 
Thankyou.

**Comment by richardkall** [comment]
I've rewritten the `App.js` container as a functional component and babel-plugin-react-transform does not support HMR for functional components, at least not yet. See https://github.com/gaearon/babel-plugin-react-transform/issues/57) for more details.

I might replace it with vanilla HMR since that is what @gaearon recommends (https://github.com/reactjs/redux/pull/1455). It's not a big issue for myself at the moment, but I might look into it.

In the meantime you can just rewrite the component as a class:

```
export class App extends Component {
  render () {
    return (
      <div className={style.root}>
        <h1>Hello World</h1>
      </div>
    );
  }
}
```

**Comment by dhoko** [comment]
It doesn't work here to.

### Step 1 - edit App.js

Output cli:

![hotreloadreact](https://cloud.githubusercontent.com/assets/713283/14554546/f599fd18-02ed-11e6-9ee4-29eb3942518a.png)


Message (devtools):

```
[HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html for more details.
main.js:1649 [HMR]  - ./client/containers/App/App.js
```

### Step 2: refresh the page


Message (devtools):

```
main.js:2720 Warning: React attempted to reuse markup in a container but the checksum was invalid. 
This generally means that you are using server rendering and the markup generated on the server was
 not what the client was expecting. React injected new markup to compensate which works but you 
have lost many of the benefits of server rendering. Instead, figure out why the markup being generated
 is different on the client or server:
 (client) 2">Hello World</h1><!-- react-text: 3 --
 (server) 2">Hello World</h1></div>
```


It works with Component :+1:

**Comment by Vistur** [comment]
@dhoko I think that the warning in the Step 2: is because the html in the server and what the client is trying to render are different. Yo may need to restart the server.

**Comment by gaearon** [comment]
@dhoko Have you converted `App` to a class first, as mentioned in https://github.com/richardkall/react-starter/issues/5#issuecomment-210133458?

**Comment by dhoko** [comment]
@gaearon 
>It works with Component :+1:

;)

**Comment by gaearon** [comment]
React Hot Loader 3 supports functional components without destroying the state.
It supersedes both React Hot Loader and React Transform, and is built on lessons learned from both.
Check it out: https://github.com/gaearon/react-hot-boilerplate/pull/61

**Comment by richardkall** [comment]
Great job as always @gaearon, thanks! Looking forward to implementing this.

**Comment by richardkall** [comment]
@gaearon Could not figure out how to get React Hot Loader 3 working with react-router, any working example of this yet?

**Comment by gaearon** [comment]
@richardkall Have you tried the latest alpha? `3.0.0-alpha.12` should just work with it, but only for routes defined with JSX and synchronous `component=`. For proper support, please track https://github.com/gaearon/react-hot-loader/issues/249 and https://github.com/reactjs/react-router/issues/2182.

**Comment by richardkall** [comment]
@gaearon What I don't understand is how I should wrap my component with `AppContainer` since the component is already inside a `<Route>`:

```
<Router history={browserHistory}>
  <Route
    component={App}
    path='/'
  />
</Router>
```

But I will look more into this later, and follow the threads you posted. Thanks!

**Comment by gaearon** [comment]
@richardkall 

```js
function Root() {
  return <Router>...</Router>
}
```

and pass `Root` to `AppContainer`.

**Comment by richardkall** [comment]
Hi!

I've now replaced React Transform HMR with React Hot Loader (3.0.0-beta.2): https://github.com/richardkall/react-starter/commit/7061c69d1a22d7d358b4d7007967350e16c00a32
