### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by MHanslo** [richardkall/react-starter#9]
Did a fresh clone, npm install and spun up a dev server.
Checking the console shows you have a issue in your config:
`main.js:37641 Uncaught ReferenceError: process is not defined`

Traced it to your config/index.js. Looks like the assignment for process.env is not done right. This essentially breaks the HMR in the app.

Node version: 6.4.0

**Comment by richardkall** [comment]
You're right, I broke this with the assignment in config/index.js. Thanks for letting me know!

I've fixed the issue.
